"""
Carga los datos de partida de Zyra (copia de la base de datos del 1 de octubre de 2026):
el club LOS GLADIADORES con sus equipos, jugadores, histórico de puntos SNP, partidos,
resultados, convocatorias y registros de convocatoria.

Se usa sobre una base de datos vacía con el esquema actual:

    python clear_database.py
    python populate_db.py

El script pide el usuario que será capitán del club (nombre de usuario, email y
contraseña). Se crea como superusuario y personal, así que también entra en el
back-office. Si el email es el de su cuenta de Google, «Entrar con Google» entra en esa
misma cuenta. Sin preguntas:

    python populate_db.py --usuario edu --email tu@email.com --sin-contrasena

(--sin-contrasena: solo podrá entrar con Google o tras `python manage.py changepassword edu`).

Cada objeto lleva ya su identificador público (PLY..., MAT...), así que las URLs son las
mismas cada vez que se carga este fichero. Las relaciones se indican con esos
identificadores.

Qué NO se carga:
- Usuarios reales ni sus emails: no se guardan en el repositorio (es público).
- La cuenta SNP del club: hay que guardarla desde la web (Jugadores > Cuenta SNP).
- Fotos de jugadores, revisiones y eliminaciones de fotos, suspensiones, emails
  bloqueados, invitaciones y envíos de informes: se empieza sin ninguno.
- Procesos programados y datos técnicos: el programador (run_scheduler) crea sus
  procesos al arrancar y el resto se regenera solo.

Los escudos de los equipos salen de populate/photos y se copian al almacenamiento de
fotos (media/) con `move_photos_to_media`.
"""
import argparse
import datetime
import getpass
import os
import sys

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "zyra.settings")
django.setup()

from django.contrib.auth import get_user_model  # noqa: E402
from django.contrib.auth.password_validation import validate_password  # noqa: E402
from django.core.exceptions import ValidationError  # noqa: E402
from django.core.management import call_command  # noqa: E402
from django.core.validators import validate_email  # noqa: E402
from django.db import transaction  # noqa: E402
from django.utils.dateparse import parse_date, parse_datetime  # noqa: E402

from call.models import Call  # noqa: E402
from callLog.models import CallLog  # noqa: E402
from core.models import Club, Membership  # noqa: E402
from match.models import Game, Match, Result  # noqa: E402
from penalty.models import Penalty  # noqa: E402
from players.models import Player, SnpScoreHistory, SnpTeamImport  # noqa: E402
from team.models import Team  # noqa: E402

User = get_user_model()


# ---------------------------------------------------------------------------
# DATOS
# ---------------------------------------------------------------------------

CLUBS = [{'public_id': 'CLBe3MhDlGw913J',
  'name': 'LOS GLADIADORES',
  'slug': 'los-gladiadores',
  'created_at': '2026-09-29T09:16:27.279016+00:00'}]


TEAMS = [{'public_id': 'TEAtkIX7SShWckF',
  'club': 'CLBe3MhDlGw913J',
  'is_own': True,
  'name': 'LOS GLADIADORES',
  'in_group': True,
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla',
  'photo': 'populate/photos/losGladiadores_photo.png'},
 {'public_id': 'TEA3fW25IIcmqim',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'LA MAGIA DEL PADEL C',
  'in_group': False,
  'location': 'Pol. La estrella, Coria del Río',
  'photo': 'populate/photos/lamagia_photo.jpg'},
 {'public_id': 'TEAsKbdNkwRZ0lr',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'CLUB DE PADEL BURGUILLOS BETA',
  'in_group': False,
  'location': 'BURGPADEL',
  'photo': 'populate/photos/burguillos_photo.jpg'},
 {'public_id': 'TEAbKItZd1HsCGo',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'LFP TOMARES MASC. B. 500',
  'in_group': False,
  'location': 'INSTALACIONES DEPORTIVAS MUNICIPALES CAMINO VIEJO',
  'photo': 'populate/photos/tomares_photo.jpg'},
 {'public_id': 'TEA3eN96hQvjCIF',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'CLUB DE PÁDEL BDB',
  'in_group': False,
  'location': 'EL REMATE PADEL SEVILLA',
  'photo': 'populate/photos/bdb_photo.png'},
 {'public_id': 'TEAG6eAPHbSRkDt',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'ASOCIACION DE PERSONAL LA CAIXA',
  'in_group': False,
  'location': 'SITING PADEL CLUB',
  'photo': 'populate/photos/La_Caixa_logo.png'},
 {'public_id': 'TEAVeKTwdLvOkw8',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'NorthPadel',
  'in_group': True,
  'location': 'Calle Gaudí, 6-20, 41220 Burguillos, Sevilla',
  'photo': ''},
 {'public_id': 'TEA2fNUXVmo93Si',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'SAMURAI PADEL',
  'in_group': True,
  'location': 'Wild Padel Indoor',
  'photo': ''},
 {'public_id': 'TEA6axYQrV0IjL6',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'ATLÉTICO ISLEÑO',
  'in_group': True,
  'location': 'Pabellón Municipal Gregorio Gabella "Gori"',
  'photo': ''},
 {'public_id': 'TEAvVn37JSNnekR',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'ICONICO 500 PLUS',
  'in_group': True,
  'location': 'ICONICO PADEL',
  'photo': ''},
 {'public_id': 'TEAlmhnRJcmOc6W',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'PADEL INDOOR FUENTES B',
  'in_group': True,
  'location': 'C. Bulería, 3, 41420 Fuentes de Andalucía, Sevilla',
  'photo': ''},
 {'public_id': 'TEAe6j9HTRFA0ii',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'RC Labradores',
  'in_group': False,
  'location': 'Labradores',
  'photo': ''},
 {'public_id': 'TEA0qpVKMTsLyHK',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'PADEL 2H - PANCELIAC 500',
  'in_group': False,
  'location': '.',
  'photo': ''},
 {'public_id': 'TEAuKhUZN7syiQ9',
  'club': 'CLBe3MhDlGw913J',
  'is_own': False,
  'name': 'CLUB PINEDA DE SEVILLA',
  'in_group': False,
  'location': '.',
  'photo': ''}]

PLAYERS = [{'public_id': 'PLYzWkzeDEWUH13',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'EDUARDO',
  'last_name': 'BUSTAMANTE LUCENA',
  'position': 'Revés',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 68500.0,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYCPxbD4jQSWOy',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'ALBERTO',
  'last_name': 'MONTAÑO LEON',
  'position': 'Revés',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 50714.29,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYnjBZHGMHnmr5',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'AURELIO',
  'last_name': 'BIELSA MARTIN',
  'position': 'Derecha',
  'skillfull_hand': 'Zurdo',
  'photo': '',
  'snp_score': 65250.0,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYQzC0bXyqBPwp',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'ALBERTO',
  'last_name': 'CASTRO LUQUE',
  'position': 'Revés',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYw7LB7ewPHULW',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'ANTONIO',
  'last_name': 'URRACO RIVERO',
  'position': 'Revés',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 42187.5,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLY9YOzy2QnlrEh',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'BORJA',
  'last_name': 'MOLINA MULLER',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 25312.5,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYH45qInS6RuPf',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'JUAN ANTONIO',
  'last_name': 'LOPEZ MUMPAO',
  'position': 'Revés',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 53437.5,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYHeiSdF9ZfLir',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'DANIEL',
  'last_name': 'CARRATALA RIUS',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 63611.11,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYnFQM6BnybeEE',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'FABRIZIO',
  'last_name': 'BRAVI',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYOYgmThkmUiFF',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'GONZALO',
  'last_name': 'SANTANA ALONSO',
  'position': 'Mixto',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 47916.67,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYB1TspsG9IiIZ',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'JUAN FRANCISCO',
  'last_name': 'ROMERO CRESPO',
  'position': 'Mixto',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 19687.5,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLY1KOAgSl1B7m4',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'JULIAN',
  'last_name': 'RUIZ DELGADO',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 53541.67,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYxHFxPQ9EL1OH',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'PABLO',
  'last_name': 'DELGADO PASCUAL',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYSMT3m89MVrCs',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'MARCELO',
  'last_name': 'DOMÍNGUEZ COSTA',
  'position': 'Derecha',
  'skillfull_hand': 'Zurdo',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYanVz8oS3njsq',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'JOSE MARIA',
  'last_name': 'CANO RAYA',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 36964.29,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYTbFWKi2gOfoT',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'TONI',
  'last_name': 'MORILLO RODRIGUEZ',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 19687.5,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYoFFu9qMRTHRL',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'JESUS',
  'last_name': 'SANCHEZ FERNANDEZ',
  'position': 'Revés',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYavwVXPAQ7LmZ',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'ALFREDO',
  'last_name': 'DELGADO',
  'position': 'Mixto',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 56250.0,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYNP7WDbz7IVP8',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'ANTONIO',
  'last_name': 'NOGUER JIMENEZ',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYFbZjsQtA4pwt',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'JORDI',
  'last_name': 'BELTRAN VEGA',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYh822ApB0OFiI',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'ANTONIO',
  'last_name': 'CARO BERMÚDEZ',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYWT8zT9fEkKR1',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'ANTONIO',
  'last_name': 'ZURITA CARRASCO',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 61093.75,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYWGVSljj1bjdc',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'Benjamin',
  'last_name': 'Caro Rodríguez',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 0.0,
  'in_team': True,
  'joined_season': '2025-2026'},
 {'public_id': 'PLYnEkUfusX8Cmr',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'FRANCISCO',
  'last_name': 'QUINTERO MORENO',
  'position': 'Mixto',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 0.0,
  'in_team': True,
  'joined_season': '2026-2027'},
 {'public_id': 'PLYOO8EiDKxOkBa',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'IVAN',
  'last_name': 'COSTA GOMEZ',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 14062.5,
  'in_team': True,
  'joined_season': '2026-2027'},
 {'public_id': 'PLYklLgCb12p11a',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'JUAN JOSE',
  'last_name': 'MARTINEZ VAZQUEZ',
  'position': 'Mixto',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 65000.0,
  'in_team': True,
  'joined_season': '2025-2026'},
 {'public_id': 'PLYjF7ImLZokdFO',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'MANUEL',
  'last_name': 'GOMEZ BELTRAN',
  'position': 'Mixto',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 0.0,
  'in_team': True,
  'joined_season': '2026-2027'},
 {'public_id': 'PLY2n1uiQJXyYsH',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'MARIANO',
  'last_name': 'MARTINEZ ALVAREZ',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 18875.0,
  'in_team': True,
  'joined_season': '2026-2027'},
 {'public_id': 'PLYPObI1TacPtrH',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'PEDRO',
  'last_name': 'KIM CHOI',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 0.0,
  'in_team': True,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYdQe3HVXZ4wdy',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'Raul',
  'last_name': 'Castañar Cintas',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 0.0,
  'in_team': True,
  'joined_season': '2026-2027'},
 {'public_id': 'PLYzU68lFDKVx55',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'PEDRO',
  'last_name': 'RAPOSO BELLERIN',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': 53125.0,
  'in_team': True,
  'joined_season': '2025-2026'},
 {'public_id': 'PLYssKfkyrm5UwD',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'Ismael',
  'last_name': '.',
  'position': 'Revés',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'},
 {'public_id': 'PLYwSp6uuieI47c',
  'club': 'CLBe3MhDlGw913J',
  'team': 'TEAtkIX7SShWckF',
  'name': 'Gon',
  'last_name': ',',
  'position': 'Derecha',
  'skillfull_hand': 'Diestro',
  'photo': '',
  'snp_score': None,
  'in_team': False,
  'joined_season': '2024-2025'}]

SNP_HISTORY = [{'public_id': 'SNHttks8aGRTqHt',
  'player': 'PLYCPxbD4jQSWOy',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 50714.29},
 {'public_id': 'SNHRhzpPINmJVHs',
  'player': 'PLYavwVXPAQ7LmZ',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 56250.0},
 {'public_id': 'SNHhad4HGUb9Byy',
  'player': 'PLYw7LB7ewPHULW',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 42187.5},
 {'public_id': 'SNH6IgCt6EWtf48',
  'player': 'PLYWT8zT9fEkKR1',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 61093.75},
 {'public_id': 'SNHgIY5ekkE21uN',
  'player': 'PLYnjBZHGMHnmr5',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 65250.0},
 {'public_id': 'SNHckkHxe1jz2pb',
  'player': 'PLYWGVSljj1bjdc',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 0.0},
 {'public_id': 'SNHj2nfTcdOlmgX',
  'player': 'PLY9YOzy2QnlrEh',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 25312.5},
 {'public_id': 'SNHWddpJMtglWGH',
  'player': 'PLYHeiSdF9ZfLir',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 63611.11},
 {'public_id': 'SNHe7ndlqp3NAJs',
  'player': 'PLYzWkzeDEWUH13',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 68500.0},
 {'public_id': 'SNHHSqwIdJM9up3',
  'player': 'PLYnEkUfusX8Cmr',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 0.0},
 {'public_id': 'SNHxgJfdwuwrNnz',
  'player': 'PLYOYgmThkmUiFF',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 47916.67},
 {'public_id': 'SNHB4p1QbWtDTyG',
  'player': 'PLYOO8EiDKxOkBa',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 14062.5},
 {'public_id': 'SNHSz6zaKKbsLkB',
  'player': 'PLYanVz8oS3njsq',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 36964.29},
 {'public_id': 'SNHnaxiJWAJG6U6',
  'player': 'PLYH45qInS6RuPf',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 53437.5},
 {'public_id': 'SNH57h1Rye5x7mi',
  'player': 'PLYB1TspsG9IiIZ',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 19687.5},
 {'public_id': 'SNHpn94Jq6E3Ri6',
  'player': 'PLYklLgCb12p11a',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 65000.0},
 {'public_id': 'SNHC1MRboMNNNSW',
  'player': 'PLY1KOAgSl1B7m4',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 53541.67},
 {'public_id': 'SNHPM7gMtoz4tMm',
  'player': 'PLYjF7ImLZokdFO',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 0.0},
 {'public_id': 'SNHsZNiWrt5hXM8',
  'player': 'PLY2n1uiQJXyYsH',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 18875.0},
 {'public_id': 'SNHqPBuLgIH54aA',
  'player': 'PLYPObI1TacPtrH',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 0.0},
 {'public_id': 'SNH44OxYErIk9HF',
  'player': 'PLYdQe3HVXZ4wdy',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 0.0},
 {'public_id': 'SNHsXspH408eB46',
  'player': 'PLYTbFWKi2gOfoT',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 19687.5},
 {'public_id': 'SNHsml1hnTr1P4H',
  'player': 'PLYzU68lFDKVx55',
  'season': '2026-2027',
  'date': '2026-10-01',
  'score': 53125.0}]

SNP_IMPORTS = [{'public_id': 'SNIL6aqblQTuQHI',
  'club': 'CLBe3MhDlGw913J',
  'source': 'web',
  'status': 'cancelled',
  'created_at': '2026-10-01T11:14:45.953245+00:00',
  'finished_at': None,
  'to_add': [],
  'existing': [{'snp_name': 'ALBERTO MONTAÑO LEON 500', 'player': 'ALBERTO MONTAÑO LEON'},
               {'snp_name': 'ALFREDO DELGADO 500', 'player': 'ALFREDO DELGADO'},
               {'snp_name': 'ANTONIO URRACO RIVERO 500', 'player': 'ANTONIO URRACO RIVERO'},
               {'snp_name': 'ANTONIO ZURITA CARRASCO 500', 'player': 'ANTONIO ZURITA CARRASCO'},
               {'snp_name': 'AURELIO BIELSA MARTIN 500', 'player': 'AURELIO BIELSA MARTIN'},
               {'snp_name': 'BORJA MOLINA MULLER Future', 'player': 'BORJA MOLINA MULLER'},
               {'snp_name': 'Benjamin Caro Rodríguez Future', 'player': 'Benjamin Caro Rodríguez'},
               {'snp_name': 'DANIEL CARRATALA RIUS 500', 'player': 'DANIEL CARRATALA RIUS'},
               {'snp_name': 'EDUARDO BUSTAMANTE LUCENA 500', 'player': 'EDUARDO BUSTAMANTE LUCENA'},
               {'snp_name': 'FRANCISCO QUINTERO MORENO Future', 'player': 'FRANCISCO QUINTERO MORENO'},
               {'snp_name': 'GONZALO SANTANA ALONSO 500', 'player': 'GONZALO SANTANA ALONSO'},
               {'snp_name': 'IVAN COSTA GOMEZ 500', 'player': 'IVAN COSTA GOMEZ'},
               {'snp_name': 'JOSE MARIA CANO RAYA Future', 'player': 'JOSE MARIA CANO RAYA'},
               {'snp_name': 'JUAN ANTONIO LOPEZ MUMPAO 500', 'player': 'JUAN ANTONIO LOPEZ MUMPAO'},
               {'snp_name': 'JUAN FRANCISCO ROMERO CRESPO 500', 'player': 'JUAN FRANCISCO ROMERO CRESPO'},
               {'snp_name': 'JUAN JOSE MARTINEZ VAZQUEZ 500', 'player': 'JUAN JOSE MARTINEZ VAZQUEZ'},
               {'snp_name': 'JULIAN RUIZ DELGADO 500', 'player': 'JULIAN RUIZ DELGADO'},
               {'snp_name': 'MANUEL GOMEZ BELTRAN Future', 'player': 'MANUEL GOMEZ BELTRAN'},
               {'snp_name': 'MARIANO MARTINEZ ALVAREZ Future', 'player': 'MARIANO MARTINEZ ALVAREZ'},
               {'snp_name': 'PEDRO KIM CHOI 500', 'player': 'PEDRO KIM CHOI'},
               {'snp_name': 'PEDRO RAPOSO BELLERIN 500', 'player': 'PEDRO RAPOSO BELLERIN'},
               {'snp_name': 'Raul Castañar Cintas Future', 'player': 'Raul Castañar Cintas'},
               {'snp_name': 'TONI MORILLO RODRIGUEZ Future', 'player': 'TONI MORILLO RODRIGUEZ'}],
  'created_players': [],
  'message': ''},
 {'public_id': 'SNIiDA9L88r1A9g',
  'club': 'CLBe3MhDlGw913J',
  'source': 'web',
  'status': 'cancelled',
  'created_at': '2026-10-01T11:16:57.232555+00:00',
  'finished_at': None,
  'to_add': [],
  'existing': [],
  'created_players': [],
  'message': ''}]

MATCHES = [{'public_id': 'MATtLTtocAuOB6r',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEA3fW25IIcmqim',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2024-10-06',
  'result': 'Victoria Local',
  'result_points': '7-5',
  'draft_mode': False,
  'season': '2024-2025',
  'location': 'Pol. La estrella, Coria del Río'},
 {'public_id': 'MATjB1GQak7E3wl',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAtkIX7SShWckF',
  'visiting': 'TEAbKItZd1HsCGo',
  'start_date': '2024-10-20',
  'result': 'Victoria Visitante',
  'result_points': '3-9',
  'draft_mode': False,
  'season': '2024-2025',
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla'},
 {'public_id': 'MATFZeEKN89Mbtb',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAsKbdNkwRZ0lr',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2024-10-27',
  'result': 'Victoria Local',
  'result_points': '10-2',
  'draft_mode': False,
  'season': '2024-2025',
  'location': 'BURGPADEL'},
 {'public_id': 'MAT81TFAk7P6cPj',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAtkIX7SShWckF',
  'visiting': 'TEAG6eAPHbSRkDt',
  'start_date': '2024-11-10',
  'result': 'Victoria Local',
  'result_points': '7-5',
  'draft_mode': False,
  'season': '2024-2025',
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla'},
 {'public_id': 'MAT2kxbkMFkELQR',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAtkIX7SShWckF',
  'visiting': 'TEAVeKTwdLvOkw8',
  'start_date': '2026-09-27',
  'result': 'Victoria Visitante',
  'result_points': '5/7',
  'draft_mode': False,
  'season': '2026-2027',
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla'},
 {'public_id': 'MATCnJ9ZOJQWQS9',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAtkIX7SShWckF',
  'visiting': 'TEAe6j9HTRFA0ii',
  'start_date': '2025-09-28',
  'result': 'Victoria Local',
  'result_points': '9/3',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla'},
 {'public_id': 'MATo1s7e2KkyEhB',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEA3fW25IIcmqim',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2025-10-05',
  'result': 'Victoria Visitante',
  'result_points': '2/10',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'Pol. La estrella, Coria del Río'},
 {'public_id': 'MATgEfDt6ZkFyAw',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAtkIX7SShWckF',
  'visiting': 'TEAVeKTwdLvOkw8',
  'start_date': '2025-10-19',
  'result': 'Victoria Local',
  'result_points': '9/3',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla'},
 {'public_id': 'MATrb08M5oUlqI1',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAtkIX7SShWckF',
  'visiting': 'TEA0qpVKMTsLyHK',
  'start_date': '2025-10-26',
  'result': 'Victoria Local',
  'result_points': '12/0',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla'},
 {'public_id': 'MATS0P8854yScRZ',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAuKhUZN7syiQ9',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2025-11-09',
  'result': 'Victoria Local',
  'result_points': '12/0',
  'draft_mode': False,
  'season': '2025-2026',
  'location': '.'},
 {'public_id': 'MAT9CiATWi6VyUj',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAe6j9HTRFA0ii',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2025-11-30',
  'result': 'Victoria Local',
  'result_points': '10/2',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'Labradores'},
 {'public_id': 'MATZ21XwxvRKpb1',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAVeKTwdLvOkw8',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2026-01-11',
  'result': 'Victoria Visitante',
  'result_points': '5/7',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'Calle Gaudí, 6-20, 41220 Burguillos, Sevilla'},
 {'public_id': 'MAT5ODut8NRTSiQ',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEA2fNUXVmo93Si',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2026-01-18',
  'result': 'Victoria Local',
  'result_points': '10/2',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'Wild Padel Indoor'},
 {'public_id': 'MATIBfmgTB09o0N',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEAtkIX7SShWckF',
  'visiting': 'TEAuKhUZN7syiQ9',
  'start_date': '2026-01-25',
  'result': 'Victoria Local',
  'result_points': '9/3',
  'draft_mode': False,
  'season': '2025-2026',
  'location': 'C. Castilla Leon, 237, 41909 Salteras, Sevilla'},
 {'public_id': 'MATDqAmU6bngCxQ',
  'club': 'CLBe3MhDlGw913J',
  'local': 'TEA6axYQrV0IjL6',
  'visiting': 'TEAtkIX7SShWckF',
  'start_date': '2026-10-04',
  'result': 'NONE',
  'result_points': 'NONE',
  'draft_mode': True,
  'season': '2026-2027',
  'location': 'Pabellón Municipal Gregorio Gabella "Gori"'}]

GAMES = [{'public_id': 'GAMxU7v0o00jJQd',
  'match': 'MATtLTtocAuOB6r',
  'n_game': 1,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYzWkzeDEWUH13',
  'player_2_visiting': 'PLY9YOzy2QnlrEh',
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMyci6y9i2wQgY',
  'match': 'MATtLTtocAuOB6r',
  'n_game': 2,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYCPxbD4jQSWOy',
  'player_2_visiting': 'PLYnjBZHGMHnmr5',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM8nRBmq3Ly27B',
  'match': 'MATtLTtocAuOB6r',
  'n_game': 3,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYHeiSdF9ZfLir',
  'player_2_visiting': 'PLYB1TspsG9IiIZ',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMvDUH1iCDcqaw',
  'match': 'MATtLTtocAuOB6r',
  'n_game': 4,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYOYgmThkmUiFF',
  'player_2_visiting': 'PLYanVz8oS3njsq',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMW7crPohwU1Rk',
  'match': 'MATtLTtocAuOB6r',
  'n_game': 5,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYFbZjsQtA4pwt',
  'player_2_visiting': 'PLYh822ApB0OFiI',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM8wWd8Oc4W8LK',
  'match': 'MATjB1GQak7E3wl',
  'n_game': 1,
  'player_1_local': 'PLYzWkzeDEWUH13',
  'player_2_local': 'PLYOYgmThkmUiFF',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM1dgWYLzrqBkF',
  'match': 'MATjB1GQak7E3wl',
  'n_game': 2,
  'player_1_local': 'PLYCPxbD4jQSWOy',
  'player_2_local': 'PLYxHFxPQ9EL1OH',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAM5p4z4TYNKoiy',
  'match': 'MATjB1GQak7E3wl',
  'n_game': 3,
  'player_1_local': 'PLYB1TspsG9IiIZ',
  'player_2_local': 'PLYSMT3m89MVrCs',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMbsJq7Oi0AmS8',
  'match': 'MATjB1GQak7E3wl',
  'n_game': 4,
  'player_1_local': 'PLYQzC0bXyqBPwp',
  'player_2_local': 'PLYTbFWKi2gOfoT',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMi3yry8k5apmM',
  'match': 'MATjB1GQak7E3wl',
  'n_game': 5,
  'player_1_local': 'PLYavwVXPAQ7LmZ',
  'player_2_local': 'PLYnFQM6BnybeEE',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMJvn9GAgn650r',
  'match': 'MATFZeEKN89Mbtb',
  'n_game': 1,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYw7LB7ewPHULW',
  'player_2_visiting': 'PLYanVz8oS3njsq',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMJcq3CntPIn5u',
  'match': 'MATFZeEKN89Mbtb',
  'n_game': 2,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLY1KOAgSl1B7m4',
  'player_2_visiting': 'PLYB1TspsG9IiIZ',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMSOSE2CPAV6OI',
  'match': 'MATFZeEKN89Mbtb',
  'n_game': 3,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYCPxbD4jQSWOy',
  'player_2_visiting': 'PLYFbZjsQtA4pwt',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM4t8IZCfqqbpm',
  'match': 'MATFZeEKN89Mbtb',
  'n_game': 4,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYzWkzeDEWUH13',
  'player_2_visiting': 'PLYh822ApB0OFiI',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMYIPjTFDXA7L8',
  'match': 'MATFZeEKN89Mbtb',
  'n_game': 5,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYH45qInS6RuPf',
  'player_2_visiting': 'PLYavwVXPAQ7LmZ',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMhwEqTr7PRpep',
  'match': 'MAT81TFAk7P6cPj',
  'n_game': 1,
  'player_1_local': 'PLYzWkzeDEWUH13',
  'player_2_local': 'PLYnjBZHGMHnmr5',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMOU53IflikzXA',
  'match': 'MAT81TFAk7P6cPj',
  'n_game': 2,
  'player_1_local': 'PLYFbZjsQtA4pwt',
  'player_2_local': 'PLYOYgmThkmUiFF',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMoNW9ULOeKUIA',
  'match': 'MAT81TFAk7P6cPj',
  'n_game': 3,
  'player_1_local': 'PLYTbFWKi2gOfoT',
  'player_2_local': 'PLYnFQM6BnybeEE',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMB0TIXzh1JbU3',
  'match': 'MAT81TFAk7P6cPj',
  'n_game': 4,
  'player_1_local': 'PLYH45qInS6RuPf',
  'player_2_local': 'PLYHeiSdF9ZfLir',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMxnwz3qFgi06i',
  'match': 'MAT81TFAk7P6cPj',
  'n_game': 5,
  'player_1_local': 'PLYCPxbD4jQSWOy',
  'player_2_local': 'PLYh822ApB0OFiI',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMHvuO5mQnuc1y',
  'match': 'MAT2kxbkMFkELQR',
  'n_game': 1,
  'player_1_local': 'PLYWT8zT9fEkKR1',
  'player_2_local': 'PLYklLgCb12p11a',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMVEVrvnsJeNQp',
  'match': 'MAT2kxbkMFkELQR',
  'n_game': 2,
  'player_1_local': 'PLYzWkzeDEWUH13',
  'player_2_local': 'PLYavwVXPAQ7LmZ',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMX6Ls09gASz9n',
  'match': 'MAT2kxbkMFkELQR',
  'n_game': 3,
  'player_1_local': 'PLYCPxbD4jQSWOy',
  'player_2_local': 'PLYHeiSdF9ZfLir',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMOmlMIQvvbNDp',
  'match': 'MAT2kxbkMFkELQR',
  'n_game': 4,
  'player_1_local': 'PLYanVz8oS3njsq',
  'player_2_local': 'PLY1KOAgSl1B7m4',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMhUEFbHkwJyQc',
  'match': 'MAT2kxbkMFkELQR',
  'n_game': 5,
  'player_1_local': 'PLYOO8EiDKxOkBa',
  'player_2_local': 'PLY9YOzy2QnlrEh',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMRvST2vFxsnsv',
  'match': 'MATCnJ9ZOJQWQS9',
  'n_game': 1,
  'player_1_local': 'PLYzWkzeDEWUH13',
  'player_2_local': 'PLYavwVXPAQ7LmZ',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM0uTupHzIvV5D',
  'match': 'MATCnJ9ZOJQWQS9',
  'n_game': 2,
  'player_1_local': 'PLYCPxbD4jQSWOy',
  'player_2_local': 'PLYHeiSdF9ZfLir',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMa45fBjdlDuMH',
  'match': 'MATCnJ9ZOJQWQS9',
  'n_game': 3,
  'player_1_local': 'PLYssKfkyrm5UwD',
  'player_2_local': 'PLYB1TspsG9IiIZ',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMKCi80MogRcL6',
  'match': 'MATCnJ9ZOJQWQS9',
  'n_game': 4,
  'player_1_local': 'PLYw7LB7ewPHULW',
  'player_2_local': 'PLYOYgmThkmUiFF',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMt1p0fUwGWpcv',
  'match': 'MATCnJ9ZOJQWQS9',
  'n_game': 5,
  'player_1_local': 'PLYklLgCb12p11a',
  'player_2_local': 'PLYWT8zT9fEkKR1',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMhTxgrKnUEwvS',
  'match': 'MATo1s7e2KkyEhB',
  'n_game': 1,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYzWkzeDEWUH13',
  'player_2_visiting': 'PLYnjBZHGMHnmr5',
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMxHyYs5B9PUvm',
  'match': 'MATo1s7e2KkyEhB',
  'n_game': 2,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLY1KOAgSl1B7m4',
  'player_2_visiting': 'PLYWT8zT9fEkKR1',
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAM1SrJTo3Hopw8',
  'match': 'MATo1s7e2KkyEhB',
  'n_game': 3,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYssKfkyrm5UwD',
  'player_2_visiting': 'PLYH45qInS6RuPf',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMSYPsiYBkGFGX',
  'match': 'MATo1s7e2KkyEhB',
  'n_game': 4,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYCPxbD4jQSWOy',
  'player_2_visiting': 'PLYnFQM6BnybeEE',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM7cPP4aNmmVjY',
  'match': 'MATo1s7e2KkyEhB',
  'n_game': 5,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYHeiSdF9ZfLir',
  'player_2_visiting': 'PLYTbFWKi2gOfoT',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAM9Qe1Majdxaol',
  'match': 'MATgEfDt6ZkFyAw',
  'n_game': 1,
  'player_1_local': 'PLYavwVXPAQ7LmZ',
  'player_2_local': 'PLYssKfkyrm5UwD',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMc7ndjuYfiKyc',
  'match': 'MATgEfDt6ZkFyAw',
  'n_game': 2,
  'player_1_local': 'PLYCPxbD4jQSWOy',
  'player_2_local': 'PLYnFQM6BnybeEE',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMcyRY3jNOWAfG',
  'match': 'MATgEfDt6ZkFyAw',
  'n_game': 3,
  'player_1_local': 'PLYHeiSdF9ZfLir',
  'player_2_local': 'PLYB1TspsG9IiIZ',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM1mq5x16rhp6p',
  'match': 'MATgEfDt6ZkFyAw',
  'n_game': 4,
  'player_1_local': 'PLYklLgCb12p11a',
  'player_2_local': 'PLYanVz8oS3njsq',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM8fbVcoPOVbTT',
  'match': 'MATgEfDt6ZkFyAw',
  'n_game': 5,
  'player_1_local': 'PLYH45qInS6RuPf',
  'player_2_local': 'PLYzU68lFDKVx55',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMHBRK9VqO3PrJ',
  'match': 'MATrb08M5oUlqI1',
  'n_game': 1,
  'player_1_local': 'PLYw7LB7ewPHULW',
  'player_2_local': 'PLYWT8zT9fEkKR1',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMMIRFFdQaZCp5',
  'match': 'MATrb08M5oUlqI1',
  'n_game': 2,
  'player_1_local': 'PLYnjBZHGMHnmr5',
  'player_2_local': 'PLY1KOAgSl1B7m4',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM5s0bbdExbG5B',
  'match': 'MATrb08M5oUlqI1',
  'n_game': 3,
  'player_1_local': 'PLYssKfkyrm5UwD',
  'player_2_local': 'PLYnFQM6BnybeEE',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMmTzgPKqTIo8z',
  'match': 'MATrb08M5oUlqI1',
  'n_game': 4,
  'player_1_local': 'PLYH45qInS6RuPf',
  'player_2_local': 'PLYOYgmThkmUiFF',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMrGba9btTF9Vw',
  'match': 'MATrb08M5oUlqI1',
  'n_game': 5,
  'player_1_local': 'PLYCPxbD4jQSWOy',
  'player_2_local': 'PLYHeiSdF9ZfLir',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMWF0OpyMEfTPV',
  'match': 'MATS0P8854yScRZ',
  'n_game': 1,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYssKfkyrm5UwD',
  'player_2_visiting': 'PLYWT8zT9fEkKR1',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMCNizjgIOLSTr',
  'match': 'MATS0P8854yScRZ',
  'n_game': 2,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYanVz8oS3njsq',
  'player_2_visiting': 'PLY9YOzy2QnlrEh',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMNhi5tNJHOjP8',
  'match': 'MATS0P8854yScRZ',
  'n_game': 3,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYB1TspsG9IiIZ',
  'player_2_visiting': 'PLYnjBZHGMHnmr5',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMh39f1NkVstNY',
  'match': 'MATS0P8854yScRZ',
  'n_game': 4,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYwSp6uuieI47c',
  'player_2_visiting': 'PLYnFQM6BnybeEE',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMmGICaoH9xfnA',
  'match': 'MATS0P8854yScRZ',
  'n_game': 5,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYTbFWKi2gOfoT',
  'player_2_visiting': 'PLYzU68lFDKVx55',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMMbCr8ZRDLT9Z',
  'match': 'MAT9CiATWi6VyUj',
  'n_game': 1,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYWT8zT9fEkKR1',
  'player_2_visiting': 'PLYssKfkyrm5UwD',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMteKDnwJoPcAb',
  'match': 'MAT9CiATWi6VyUj',
  'n_game': 2,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYH45qInS6RuPf',
  'player_2_visiting': 'PLYOYgmThkmUiFF',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMZQfVS97b5Rx9',
  'match': 'MAT9CiATWi6VyUj',
  'n_game': 3,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLY1KOAgSl1B7m4',
  'player_2_visiting': 'PLYanVz8oS3njsq',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMPOFJJOIH32Ca',
  'match': 'MAT9CiATWi6VyUj',
  'n_game': 4,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYnFQM6BnybeEE',
  'player_2_visiting': 'PLYCPxbD4jQSWOy',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMFrN79FH480fS',
  'match': 'MAT9CiATWi6VyUj',
  'n_game': 5,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYwSp6uuieI47c',
  'player_2_visiting': 'PLYavwVXPAQ7LmZ',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMELapo92s629w',
  'match': 'MATZ21XwxvRKpb1',
  'n_game': 1,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYnjBZHGMHnmr5',
  'player_2_visiting': 'PLYH45qInS6RuPf',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMk3DJebYGzpfX',
  'match': 'MATZ21XwxvRKpb1',
  'n_game': 2,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYw7LB7ewPHULW',
  'player_2_visiting': 'PLYavwVXPAQ7LmZ',
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMdtNB46UHQFqg',
  'match': 'MATZ21XwxvRKpb1',
  'n_game': 3,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYWT8zT9fEkKR1',
  'player_2_visiting': 'PLYklLgCb12p11a',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMVWfYM70LV1TE',
  'match': 'MATZ21XwxvRKpb1',
  'n_game': 4,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYHeiSdF9ZfLir',
  'player_2_visiting': 'PLY1KOAgSl1B7m4',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMNm0oVNjvvRR6',
  'match': 'MATZ21XwxvRKpb1',
  'n_game': 5,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYOYgmThkmUiFF',
  'player_2_visiting': 'PLYssKfkyrm5UwD',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMfY98H9ZHz5ry',
  'match': 'MAT5ODut8NRTSiQ',
  'n_game': 1,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYnjBZHGMHnmr5',
  'player_2_visiting': 'PLYHeiSdF9ZfLir',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMsxDA9D0qQYKV',
  'match': 'MAT5ODut8NRTSiQ',
  'n_game': 2,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYzWkzeDEWUH13',
  'player_2_visiting': 'PLYanVz8oS3njsq',
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMo2DhKMJbyav5',
  'match': 'MAT5ODut8NRTSiQ',
  'n_game': 3,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYH45qInS6RuPf',
  'player_2_visiting': 'PLYw7LB7ewPHULW',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAM1uzamaSpmjN8',
  'match': 'MAT5ODut8NRTSiQ',
  'n_game': 4,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLYssKfkyrm5UwD',
  'player_2_visiting': 'PLYzU68lFDKVx55',
  'score': 2,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMLhkvaKcOuynV',
  'match': 'MAT5ODut8NRTSiQ',
  'n_game': 5,
  'player_1_local': None,
  'player_2_local': None,
  'player_1_visiting': 'PLY9YOzy2QnlrEh',
  'player_2_visiting': 'PLY1KOAgSl1B7m4',
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMyOcrALAA2Pgr',
  'match': 'MATIBfmgTB09o0N',
  'n_game': 1,
  'player_1_local': 'PLYzWkzeDEWUH13',
  'player_2_local': 'PLYWT8zT9fEkKR1',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMqQiycZGrLwGD',
  'match': 'MATIBfmgTB09o0N',
  'n_game': 2,
  'player_1_local': 'PLYHeiSdF9ZfLir',
  'player_2_local': 'PLYanVz8oS3njsq',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 3,
  'winner': 'Visitante',
  'draft_mode': False},
 {'public_id': 'GAMJaMQLvsypaZe',
  'match': 'MATIBfmgTB09o0N',
  'n_game': 3,
  'player_1_local': 'PLYssKfkyrm5UwD',
  'player_2_local': 'PLYOYgmThkmUiFF',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMVMNsJCTylloM',
  'match': 'MATIBfmgTB09o0N',
  'n_game': 4,
  'player_1_local': 'PLYH45qInS6RuPf',
  'player_2_local': 'PLYnFQM6BnybeEE',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False},
 {'public_id': 'GAMjwqptgPiTDGT',
  'match': 'MATIBfmgTB09o0N',
  'n_game': 5,
  'player_1_local': 'PLYzU68lFDKVx55',
  'player_2_local': 'PLYwSp6uuieI47c',
  'player_1_visiting': None,
  'player_2_visiting': None,
  'score': 2,
  'winner': 'Local',
  'draft_mode': False}]

RESULTS = [{'public_id': 'RESKUpt8DN1FJ5U',
  'game': 'GAMxU7v0o00jJQd',
  'result': 'Victoria Visitante',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 4,
  'set2_visiting': 6,
  'set3_local': 3,
  'set3_visiting': 6,
  'draft_mode': False},
 {'public_id': 'RESPgXnqGmmOZUp',
  'game': 'GAMyci6y9i2wQgY',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESjG6991LUqbeA',
  'game': 'GAM8nRBmq3Ly27B',
  'result': 'Victoria Visitante',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 4,
  'set2_visiting': 6,
  'set3_local': 5,
  'set3_visiting': 7,
  'draft_mode': False},
 {'public_id': 'RESolX6vs0MW22W',
  'game': 'GAMvDUH1iCDcqaw',
  'result': 'Victoria Local',
  'set1_local': 7,
  'set1_visiting': 6,
  'set2_local': 4,
  'set2_visiting': 6,
  'set3_local': 6,
  'set3_visiting': 3,
  'draft_mode': False},
 {'public_id': 'RES4NkfGAYtMBVi',
  'game': 'GAMW7crPohwU1Rk',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 2,
  'set2_visiting': 6,
  'set3_local': 6,
  'set3_visiting': 4,
  'draft_mode': False},
 {'public_id': 'RESVg3ECI3cuciU',
  'game': 'GAM8wWd8Oc4W8LK',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESAIBtOTc8jBNZ',
  'game': 'GAM1dgWYLzrqBkF',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 7,
  'set2_visiting': 5,
  'set3_local': 4,
  'set3_visiting': 6,
  'draft_mode': False},
 {'public_id': 'RES44tTIds2zxyR',
  'game': 'GAM5p4z4TYNKoiy',
  'result': 'Victoria Visitante',
  'set1_local': 4,
  'set1_visiting': 6,
  'set2_local': 2,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESTqesfMt8YRlw',
  'game': 'GAMbsJq7Oi0AmS8',
  'result': 'Victoria Visitante',
  'set1_local': 2,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESIMmOtTfp6Xof',
  'game': 'GAMi3yry8k5apmM',
  'result': 'Victoria Visitante',
  'set1_local': 7,
  'set1_visiting': 6,
  'set2_local': 5,
  'set2_visiting': 7,
  'set3_local': 3,
  'set3_visiting': 6,
  'draft_mode': False},
 {'public_id': 'RESVRoNlNiwg3QF',
  'game': 'GAMJvn9GAgn650r',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESLXxZNZRUqdKm',
  'game': 'GAMJcq3CntPIn5u',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RES8eucQl3H5Vnq',
  'game': 'GAMSOSE2CPAV6OI',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESfdpEbH7zg64L',
  'game': 'GAM4t8IZCfqqbpm',
  'result': 'Victoria Visitante',
  'set1_local': 6,
  'set1_visiting': 2,
  'set2_local': 2,
  'set2_visiting': 6,
  'set3_local': 6,
  'set3_visiting': 7,
  'draft_mode': False},
 {'public_id': 'RESJ9s0qoh4d7v9',
  'game': 'GAMYIPjTFDXA7L8',
  'result': 'Victoria Local',
  'set1_local': 7,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESU9jnGqvnPaZ4',
  'game': 'GAMhwEqTr7PRpep',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 7,
  'set2_visiting': 5,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESApjRvIjB0MHp',
  'game': 'GAMOU53IflikzXA',
  'result': 'Victoria Visitante',
  'set1_local': 1,
  'set1_visiting': 6,
  'set2_local': 1,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESSDRGgd6DHg6y',
  'game': 'GAMoNW9ULOeKUIA',
  'result': 'Victoria Visitante',
  'set1_local': 2,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': 3,
  'set3_visiting': 6,
  'draft_mode': False},
 {'public_id': 'RESkqFvlt6DJY6P',
  'game': 'GAMB0TIXzh1JbU3',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESQKGKeIBtLIGa',
  'game': 'GAMxnwz3qFgi06i',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': False},
 {'public_id': 'RESGSFNoG7HJXn8',
  'game': 'GAMVEVrvnsJeNQp',
  'result': 'Victoria Local',
  'set1_local': 7,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES51gnipcPGexX',
  'game': 'GAMOmlMIQvvbNDp',
  'result': 'Victoria Visitante',
  'set1_local': 4,
  'set1_visiting': 6,
  'set2_local': 5,
  'set2_visiting': 7,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESqcfkeyhvbbCQ',
  'game': 'GAMRvST2vFxsnsv',
  'result': 'Victoria Local',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 7,
  'set2_visiting': 6,
  'set3_local': 7,
  'set3_visiting': 5,
  'draft_mode': True},
 {'public_id': 'RESCVF8KZHwymSN',
  'game': 'GAM0uTupHzIvV5D',
  'result': 'Victoria Visitante',
  'set1_local': 5,
  'set1_visiting': 7,
  'set2_local': 6,
  'set2_visiting': 7,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESdBpPdB6CcHB0',
  'game': 'GAMa45fBjdlDuMH',
  'result': 'Victoria Local',
  'set1_local': 7,
  'set1_visiting': 5,
  'set2_local': 6,
  'set2_visiting': 1,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESe6HtlybWEP5H',
  'game': 'GAMKCi80MogRcL6',
  'result': 'Victoria Local',
  'set1_local': 7,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES0E6uXpRH7CEk',
  'game': 'GAMt1p0fUwGWpcv',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 1,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESm21XlDJFAD5i',
  'game': 'GAMhTxgrKnUEwvS',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESzQX1mmcGOpxy',
  'game': 'GAMxHyYs5B9PUvm',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES3ea7slzIdzdh',
  'game': 'GAM1SrJTo3Hopw8',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESkeWGtF1GHHBe',
  'game': 'GAMSYPsiYBkGFGX',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES3sFd9BFp2rO7',
  'game': 'GAM7cPP4aNmmVjY',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES7YnKLVD8fSrI',
  'game': 'GAM9Qe1Majdxaol',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 7,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES8RjCNJdSTKoU',
  'game': 'GAMc7ndjuYfiKyc',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'REShwTyOTFZ4Ilg',
  'game': 'GAMcyRY3jNOWAfG',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESrE5U6D28lLJn',
  'game': 'GAM1mq5x16rhp6p',
  'result': 'Victoria Local',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 1,
  'set3_local': 6,
  'set3_visiting': 0,
  'draft_mode': True},
 {'public_id': 'RESUSuGZMrerhAO',
  'game': 'GAM8fbVcoPOVbTT',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESNqG5qhguol7d',
  'game': 'GAMHBRK9VqO3PrJ',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESDzr8Ihb1M1Gl',
  'game': 'GAMMIRFFdQaZCp5',
  'result': 'Victoria Local',
  'set1_local': 7,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 1,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESVNVoCaw8zoIV',
  'game': 'GAM5s0bbdExbG5B',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 1,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESdgmgGXuKysl2',
  'game': 'GAMmTzgPKqTIo8z',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 1,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESMFTgUT8qBBUy',
  'game': 'GAMrGba9btTF9Vw',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 1,
  'set2_local': 6,
  'set2_visiting': 1,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESmk8YyjVh7l4w',
  'game': 'GAMWF0OpyMEfTPV',
  'result': 'Victoria Local',
  'set1_local': 7,
  'set1_visiting': 5,
  'set2_local': 7,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESIDp0W4eUdHEz',
  'game': 'GAMCNizjgIOLSTr',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 1,
  'set2_local': 6,
  'set2_visiting': 0,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESAywOIrOWPdQl',
  'game': 'GAMNhi5tNJHOjP8',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES3bsDhcfVOUV8',
  'game': 'GAMh39f1NkVstNY',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESOKPfbWHlXXkf',
  'game': 'GAMmGICaoH9xfnA',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 7,
  'set3_local': 6,
  'set3_visiting': 1,
  'draft_mode': True},
 {'public_id': 'RES6QpUtv1dlUT2',
  'game': 'GAMELapo92s629w',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESti3Wh8sVcpUY',
  'game': 'GAMk3DJebYGzpfX',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 4,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESG8eYBOOp0spv',
  'game': 'GAMdtNB46UHQFqg',
  'result': 'Victoria Visitante',
  'set1_local': 2,
  'set1_visiting': 6,
  'set2_local': 1,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESBthgxpOwqlSy',
  'game': 'GAMVWfYM70LV1TE',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 0,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES5DfwsxlNgUNT',
  'game': 'GAMNm0oVNjvvRR6',
  'result': 'Victoria Visitante',
  'set1_local': 2,
  'set1_visiting': 6,
  'set2_local': 2,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES5NpuMv9oaspo',
  'game': 'GAMfY98H9ZHz5ry',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESi3YTxA1yBqL2',
  'game': 'GAMsxDA9D0qQYKV',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESmGy0QpBhEgVn',
  'game': 'GAMo2DhKMJbyav5',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES1nPfOX0SYfEp',
  'game': 'GAM1uzamaSpmjN8',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES9GjXjHQHKhJF',
  'game': 'GAMLhkvaKcOuynV',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESZSGZxR4Gxy3s',
  'game': 'GAMHvuO5mQnuc1y',
  'result': 'Victoria Visitante',
  'set1_local': 2,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': 4,
  'set3_visiting': 6,
  'draft_mode': True},
 {'public_id': 'RESmaRyGG6F8lpZ',
  'game': 'GAMhUEFbHkwJyQc',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESNXYJYTXq47jl',
  'game': 'GAMX6Ls09gASz9n',
  'result': 'Victoria Visitante',
  'set1_local': 4,
  'set1_visiting': 6,
  'set2_local': 7,
  'set2_visiting': 5,
  'set3_local': 2,
  'set3_visiting': 6,
  'draft_mode': True},
 {'public_id': 'RESr41NnySVQQtv',
  'game': 'GAMyOcrALAA2Pgr',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESKYRi5SvaVR9Q',
  'game': 'GAMqQiycZGrLwGD',
  'result': 'Victoria Visitante',
  'set1_local': 1,
  'set1_visiting': 6,
  'set2_local': 6,
  'set2_visiting': 4,
  'set3_local': 1,
  'set3_visiting': 6,
  'draft_mode': True},
 {'public_id': 'RESBOcI0J3f2HfS',
  'game': 'GAMJaMQLvsypaZe',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 7,
  'set2_local': 7,
  'set2_visiting': 6,
  'set3_local': 7,
  'set3_visiting': 5,
  'draft_mode': True},
 {'public_id': 'RESPrZkMETDmJMA',
  'game': 'GAMVMNsJCTylloM',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 7,
  'set2_local': 7,
  'set2_visiting': 6,
  'set3_local': 7,
  'set3_visiting': 6,
  'draft_mode': True},
 {'public_id': 'RESjjHEbG7hO30R',
  'game': 'GAMjwqptgPiTDGT',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 4,
  'set2_local': 6,
  'set2_visiting': 2,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESzY74zxIrieCR',
  'game': 'GAMMbCr8ZRDLT9Z',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESJxn2Jo5ZdMbj',
  'game': 'GAMteKDnwJoPcAb',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RES4tgZ5Mq2ScuD',
  'game': 'GAMZQfVS97b5Rx9',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESyFEX9U7a70hQ',
  'game': 'GAMPOFJJOIH32Ca',
  'result': 'Victoria Visitante',
  'set1_local': 3,
  'set1_visiting': 6,
  'set2_local': 3,
  'set2_visiting': 6,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True},
 {'public_id': 'RESpcerEZQVd1N2',
  'game': 'GAMFrN79FH480fS',
  'result': 'Victoria Local',
  'set1_local': 6,
  'set1_visiting': 3,
  'set2_local': 6,
  'set2_visiting': 3,
  'set3_local': None,
  'set3_visiting': None,
  'draft_mode': True}]

CALLS = [{'public_id': 'CALKnzVwXhaHoIl',
  'match': 'MATtLTtocAuOB6r',
  'draft_mode': False,
  'players': ['PLYzWkzeDEWUH13',
              'PLYCPxbD4jQSWOy',
              'PLYnjBZHGMHnmr5',
              'PLY9YOzy2QnlrEh',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYOYgmThkmUiFF',
              'PLYB1TspsG9IiIZ',
              'PLYxHFxPQ9EL1OH',
              'PLYanVz8oS3njsq',
              'PLYTbFWKi2gOfoT',
              'PLYFbZjsQtA4pwt',
              'PLYh822ApB0OFiI']},
 {'public_id': 'CALaEe9yW2HXGv5',
  'match': 'MATjB1GQak7E3wl',
  'draft_mode': False,
  'players': ['PLYzWkzeDEWUH13',
              'PLYCPxbD4jQSWOy',
              'PLYnjBZHGMHnmr5',
              'PLYQzC0bXyqBPwp',
              'PLYHeiSdF9ZfLir',
              'PLYnFQM6BnybeEE',
              'PLYOYgmThkmUiFF',
              'PLYB1TspsG9IiIZ',
              'PLY1KOAgSl1B7m4',
              'PLYxHFxPQ9EL1OH',
              'PLYSMT3m89MVrCs',
              'PLYTbFWKi2gOfoT',
              'PLYavwVXPAQ7LmZ',
              'PLYFbZjsQtA4pwt']},
 {'public_id': 'CAL6cWWIwZLqKhQ',
  'match': 'MATFZeEKN89Mbtb',
  'draft_mode': False,
  'players': ['PLYzWkzeDEWUH13',
              'PLYCPxbD4jQSWOy',
              'PLYQzC0bXyqBPwp',
              'PLYw7LB7ewPHULW',
              'PLYH45qInS6RuPf',
              'PLYnFQM6BnybeEE',
              'PLYB1TspsG9IiIZ',
              'PLY1KOAgSl1B7m4',
              'PLYanVz8oS3njsq',
              'PLYavwVXPAQ7LmZ',
              'PLYFbZjsQtA4pwt',
              'PLYh822ApB0OFiI']},
 {'public_id': 'CAL445DRJzFQhkF',
  'match': 'MAT81TFAk7P6cPj',
  'draft_mode': False,
  'players': ['PLYzWkzeDEWUH13',
              'PLYCPxbD4jQSWOy',
              'PLYnjBZHGMHnmr5',
              'PLYQzC0bXyqBPwp',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYnFQM6BnybeEE',
              'PLYOYgmThkmUiFF',
              'PLY1KOAgSl1B7m4',
              'PLYTbFWKi2gOfoT',
              'PLYFbZjsQtA4pwt',
              'PLYh822ApB0OFiI']},
 {'public_id': 'CALhe7ae3wfySJC',
  'match': 'MAT2kxbkMFkELQR',
  'draft_mode': False,
  'players': ['PLYzWkzeDEWUH13',
              'PLYCPxbD4jQSWOy',
              'PLYw7LB7ewPHULW',
              'PLY9YOzy2QnlrEh',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYOYgmThkmUiFF',
              'PLY1KOAgSl1B7m4',
              'PLYTbFWKi2gOfoT',
              'PLYavwVXPAQ7LmZ',
              'PLYWT8zT9fEkKR1',
              'PLYOO8EiDKxOkBa',
              'PLYanVz8oS3njsq',
              'PLYPObI1TacPtrH',
              'PLYdQe3HVXZ4wdy',
              'PLYnEkUfusX8Cmr',
              'PLYklLgCb12p11a']},
 {'public_id': 'CALONfpFlzaOLF5',
  'match': 'MATCnJ9ZOJQWQS9',
  'draft_mode': False,
  'players': ['PLYzU68lFDKVx55',
              'PLYzWkzeDEWUH13',
              'PLYCPxbD4jQSWOy',
              'PLYssKfkyrm5UwD',
              'PLYwSp6uuieI47c',
              'PLYw7LB7ewPHULW',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYOYgmThkmUiFF',
              'PLYB1TspsG9IiIZ',
              'PLY1KOAgSl1B7m4',
              'PLYTbFWKi2gOfoT',
              'PLYavwVXPAQ7LmZ',
              'PLYWT8zT9fEkKR1',
              'PLYklLgCb12p11a']},
 {'public_id': 'CALmO7bY4FUnmSl',
  'match': 'MATo1s7e2KkyEhB',
  'draft_mode': False,
  'players': ['PLYzWkzeDEWUH13',
              'PLYCPxbD4jQSWOy',
              'PLYnjBZHGMHnmr5',
              'PLYssKfkyrm5UwD',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLY1KOAgSl1B7m4',
              'PLYTbFWKi2gOfoT',
              'PLYWT8zT9fEkKR1',
              'PLYnFQM6BnybeEE']},
 {'public_id': 'CALMTSkFGulvNXM',
  'match': 'MATgEfDt6ZkFyAw',
  'draft_mode': False,
  'players': ['PLYzU68lFDKVx55',
              'PLYssKfkyrm5UwD',
              'PLYCPxbD4jQSWOy',
              'PLYwSp6uuieI47c',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYnFQM6BnybeEE',
              'PLYB1TspsG9IiIZ',
              'PLYTbFWKi2gOfoT',
              'PLYavwVXPAQ7LmZ',
              'PLYanVz8oS3njsq',
              'PLYklLgCb12p11a']},
 {'public_id': 'CAL6o2lt7JICavw',
  'match': 'MATrb08M5oUlqI1',
  'draft_mode': False,
  'players': ['PLYzU68lFDKVx55',
              'PLYssKfkyrm5UwD',
              'PLYCPxbD4jQSWOy',
              'PLYnjBZHGMHnmr5',
              'PLYw7LB7ewPHULW',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYnFQM6BnybeEE',
              'PLYOYgmThkmUiFF',
              'PLYB1TspsG9IiIZ',
              'PLY1KOAgSl1B7m4',
              'PLYTbFWKi2gOfoT',
              'PLYWT8zT9fEkKR1',
              'PLYanVz8oS3njsq']},
 {'public_id': 'CALhPmbMFKfZ1mO',
  'match': 'MATS0P8854yScRZ',
  'draft_mode': False,
  'players': ['PLYzU68lFDKVx55',
              'PLYssKfkyrm5UwD',
              'PLYwSp6uuieI47c',
              'PLYnjBZHGMHnmr5',
              'PLY9YOzy2QnlrEh',
              'PLYH45qInS6RuPf',
              'PLYnFQM6BnybeEE',
              'PLYOYgmThkmUiFF',
              'PLYB1TspsG9IiIZ',
              'PLY1KOAgSl1B7m4',
              'PLYanVz8oS3njsq',
              'PLYTbFWKi2gOfoT',
              'PLYWT8zT9fEkKR1',
              'PLYklLgCb12p11a']},
 {'public_id': 'CALJTir3q7Hn8hR',
  'match': 'MAT9CiATWi6VyUj',
  'draft_mode': False,
  'players': ['PLYssKfkyrm5UwD',
              'PLYwSp6uuieI47c',
              'PLYH45qInS6RuPf',
              'PLYnFQM6BnybeEE',
              'PLYOYgmThkmUiFF',
              'PLY1KOAgSl1B7m4',
              'PLYanVz8oS3njsq',
              'PLYavwVXPAQ7LmZ',
              'PLYWT8zT9fEkKR1',
              'PLYCPxbD4jQSWOy']},
 {'public_id': 'CALs2KVQx1mBDWl',
  'match': 'MATZ21XwxvRKpb1',
  'draft_mode': False,
  'players': ['PLYzWkzeDEWUH13',
              'PLYssKfkyrm5UwD',
              'PLYnjBZHGMHnmr5',
              'PLYw7LB7ewPHULW',
              'PLY9YOzy2QnlrEh',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYnFQM6BnybeEE',
              'PLYOYgmThkmUiFF',
              'PLY1KOAgSl1B7m4',
              'PLYavwVXPAQ7LmZ',
              'PLYWT8zT9fEkKR1',
              'PLYklLgCb12p11a']},
 {'public_id': 'CALZEK3sZvE1myI',
  'match': 'MAT5ODut8NRTSiQ',
  'draft_mode': False,
  'players': ['PLYzU68lFDKVx55',
              'PLYzWkzeDEWUH13',
              'PLYssKfkyrm5UwD',
              'PLYnjBZHGMHnmr5',
              'PLYwSp6uuieI47c',
              'PLYw7LB7ewPHULW',
              'PLY9YOzy2QnlrEh',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLY1KOAgSl1B7m4',
              'PLYanVz8oS3njsq',
              'PLYavwVXPAQ7LmZ']},
 {'public_id': 'CALmIdj4W71YLO8',
  'match': 'MATIBfmgTB09o0N',
  'draft_mode': False,
  'players': ['PLYzU68lFDKVx55',
              'PLYzWkzeDEWUH13',
              'PLYssKfkyrm5UwD',
              'PLYwSp6uuieI47c',
              'PLYH45qInS6RuPf',
              'PLYHeiSdF9ZfLir',
              'PLYnFQM6BnybeEE',
              'PLYOYgmThkmUiFF',
              'PLYanVz8oS3njsq',
              'PLYWT8zT9fEkKR1']}]

CALL_LOGS = [{'public_id': 'LOG7efpG17WUmlG',
  'call': 'CALhe7ae3wfySJC',
  'text': 'Jugadores añadidos con la convocatoria abierta: FRANCISCO el día 27-09-2026 18:10:48;Jugadores añadidos con '
          'la convocatoria abierta: JUAN JOSE el día 27-09-2026 18:12:33;'},
 {'public_id': 'LOGg8sO7eGsALJb', 'call': 'CALONfpFlzaOLF5', 'text': ''},
 {'public_id': 'LOGeknWmI8dZcFA',
  'call': 'CALmO7bY4FUnmSl',
  'text': 'Jugadores añadidos con la convocatoria abierta: FABRIZIO el día 27-09-2026 18:48:50;'},
 {'public_id': 'LOG99zgVYoO72w4', 'call': 'CALMTSkFGulvNXM', 'text': ''},
 {'public_id': 'LOG0yuetLtZwePG', 'call': 'CAL6o2lt7JICavw', 'text': ''},
 {'public_id': 'LOGQYX69HrEUoz7', 'call': 'CALhPmbMFKfZ1mO', 'text': ''},
 {'public_id': 'LOGzGWn0mh7RxZC',
  'call': 'CALJTir3q7Hn8hR',
  'text': 'Jugadores añadidos con la convocatoria abierta: ALBERTO el día 27-09-2026 19:25:02;'},
 {'public_id': 'LOGUNlmDBfYuMvM', 'call': 'CALs2KVQx1mBDWl', 'text': ''},
 {'public_id': 'LOGeAEltJWo9wpF', 'call': 'CALZEK3sZvE1myI', 'text': ''},
 {'public_id': 'LOGqNlMSfolrxpt', 'call': 'CALmIdj4W71YLO8', 'text': ''}]

PENALTIES = []


# ---------------------------------------------------------------------------
# CARGA
# ---------------------------------------------------------------------------

def _dt(value):
    return parse_datetime(value) if value else None


def _create(label, model, rows, build, keep_dates=()):
    """
    Crea las filas con bulk_create (sin pasar por save(): los datos ya vienen limpios)
    y devuelve {public_id: objeto}. Los campos auto_now_add se fijan después, porque
    bulk_create los rellena con la fecha actual.
    """
    objs = model.objects.bulk_create([build(row) for row in rows])
    for row in rows:
        dates = {f: _dt(row[f]) for f in keep_dates if row.get(f)}
        if dates:
            model.objects.filter(public_id=row["public_id"]).update(**dates)
    by_id = model.objects.in_bulk([o.public_id for o in objs], field_name="public_id")
    print(f"  {label}: {len(by_id)}")
    return by_id


def _ask(label, value, check):
    while True:
        value = (value or input(f"{label}: ")).strip()
        try:
            check(value)
            return value
        except ValidationError as exc:
            print(f"  {' '.join(exc.messages)}")
            value = ""


def _check_username(value):
    if not value:
        raise ValidationError("Escribe un nombre de usuario.")
    User.username_validator(value)


def ask_captain(args):
    """(usuario, email, contraseña o None) del capitán del club."""
    username = _ask("Usuario del capitán", args.usuario, _check_username)
    email = _ask("Email", args.email, validate_email).lower()
    if args.sin_contrasena:
        return username, email, None
    while True:
        password = getpass.getpass("Contraseña (vacía = sin contraseña, entra con Google): ")
        if not password:
            return username, email, None
        try:
            validate_password(password, User(username=username, email=email))
        except ValidationError as exc:
            print(f"  {' '.join(exc.messages)}")
            continue
        if getpass.getpass("Repítela: ") == password:
            return username, email, password
        print("  No coinciden, prueba otra vez.")


@transaction.atomic
def populate(username, email, password):
    captain = User(username=username, email=email, is_staff=True, is_superuser=True)
    if password:
        captain.set_password(password)
    else:
        captain.set_unusable_password()
    captain.save()
    print(f"  capitán: {captain.username} ({captain.email}), también superusuario")

    clubs = _create("clubes", Club, CLUBS, lambda r: Club(public_id=r["public_id"], name=r["name"], slug=r["slug"]),
                    keep_dates=["created_at"])
    for club in clubs.values():
        Membership.objects.create(user=captain, club=club, role=Membership.ADMIN)
    teams = _create("equipos", Team, TEAMS, lambda r: Team(
        public_id=r["public_id"], club=clubs.get(r["club"]), is_own=r["is_own"], name=r["name"],
        in_group=r["in_group"], location=r["location"], photo=r["photo"]))
    players = _create("jugadores", Player, PLAYERS, lambda r: Player(
        public_id=r["public_id"], club=clubs.get(r["club"]), team=teams[r["team"]], name=r["name"],
        last_name=r["last_name"], position=r["position"], skillfull_hand=r["skillfull_hand"], photo=r["photo"],
        snp_score=r["snp_score"], in_team=r["in_team"], joined_season=r["joined_season"]))
    _create("histórico de puntos SNP", SnpScoreHistory, SNP_HISTORY, lambda r: SnpScoreHistory(
        public_id=r["public_id"], player=players[r["player"]], season=r["season"], date=parse_date(r["date"]),
        score=r["score"]))
    _create("completar equipo", SnpTeamImport, SNP_IMPORTS, lambda r: SnpTeamImport(
        public_id=r["public_id"], club=clubs[r["club"]], source=r["source"], status=r["status"],
        started_by=captain, finished_at=_dt(r["finished_at"]), to_add=r["to_add"],
        existing=r["existing"], created_players=r["created_players"], message=r["message"]),
        keep_dates=["created_at"])

    matches = _create("enfrentamientos", Match, MATCHES, lambda r: Match(
        public_id=r["public_id"], club=clubs.get(r["club"]), local=teams.get(r["local"]),
        visiting=teams.get(r["visiting"]), start_date=parse_date(r["start_date"]), result=r["result"],
        result_points=r["result_points"], draft_mode=r["draft_mode"], season=r["season"], location=r["location"]))
    games = _create("partidos", Game, GAMES, lambda r: Game(
        public_id=r["public_id"], match=matches[r["match"]], n_game=r["n_game"],
        player_1_local=players.get(r["player_1_local"]), player_2_local=players.get(r["player_2_local"]),
        player_1_visiting=players.get(r["player_1_visiting"]), player_2_visiting=players.get(r["player_2_visiting"]),
        score=r["score"], winner=r["winner"], draft_mode=r["draft_mode"]))
    _create("resultados", Result, RESULTS, lambda r: Result(
        public_id=r["public_id"], game=games[r["game"]], result=r["result"],
        set1_local=r["set1_local"], set1_visiting=r["set1_visiting"], set2_local=r["set2_local"],
        set2_visiting=r["set2_visiting"], set3_local=r["set3_local"], set3_visiting=r["set3_visiting"],
        draft_mode=r["draft_mode"]))

    calls = _create("convocatorias", Call, CALLS, lambda r: Call(public_id=r["public_id"], match=matches[r["match"]],
                                                                 draft_mode=r["draft_mode"]))
    Call.players.through.objects.bulk_create([
        Call.players.through(call=calls[r["public_id"]], player=players[p]) for r in CALLS for p in r["players"]
    ])
    _create("registros de convocatoria", CallLog, CALL_LOGS,
            lambda r: CallLog(public_id=r["public_id"], call=calls[r["call"]], text=r["text"]))
    _create("penalizaciones", Penalty, PENALTIES, lambda r: Penalty(
        public_id=r["public_id"], player=players[r["player"]], call=calls[r["call"]], reason=r["reason"]))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Carga los datos de partida de Zyra en una base de datos vacía.")
    parser.add_argument("--usuario", help="usuario del capitán del club (si no, se pregunta)")
    parser.add_argument("--email", help="email del capitán (si no, se pregunta)")
    parser.add_argument("--sin-contrasena", action="store_true",
                        help="el capitán no tiene contraseña: entra con Google o tras changepassword")
    args = parser.parse_args()
    if Club.objects.exists() or User.objects.exists():
        sys.exit("La base de datos ya tiene datos. Vacíala antes con: python clear_database.py")
    populate(*ask_captain(args))
    # Copia los escudos de ejemplo (populate/photos) al almacenamiento de fotos (media/).
    call_command("move_photos_to_media")
    print(f"Listo ({datetime.datetime.now():%d/%m/%Y %H:%M}). Guarda la cuenta SNP del club desde la web si la usas.")
