# Generated by Django 5.1.2 on 2026-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("admin", "Capitán"), ("member", "Miembro (solo lectura)")],
                default="member",
                max_length=10,
            ),
        ),
    ]
