# Generated by Django 5.1.2 on 2026-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_membership_role_capitan"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
