# Generated by Django 5.1.2 on 2026-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_existing_photos_to_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="suspension_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
