# Generated by Django 5.1.2 on 2026-10-03 17:38

from django.db import migrations, models


def reviewed_to_approved(apps, schema_editor):
    """«Revisada por el personal» y «Validada» eran lo mismo (foto correcta): queda solo «Validada»."""
    apps.get_model("core", "PhotoCheck").objects.filter(status="reviewed").update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_blocked_email"),
    ]

    operations = [
        migrations.RunPython(reviewed_to_approved, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="photocheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Validada"),
                    ("rejected", "Rechazada"),
                    ("unchecked", "Pendiente de revisar"),
                ],
                max_length=10,
            ),
        ),
    ]
