# Generated by Django 5.1.2 on 2026-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
