# Generated by Django 5.1.2 on 2026-10-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_own", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("in_group", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="static/team"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="core.club",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("club", "name"), name="unique_team_name_per_club"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_own", True)),
                        fields=("club",),
                        name="unique_own_team_per_club",
                    ),
                ],
            },
        ),
    ]
