# Generated by Django 5.1.2 on 2026-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_team_name_per_club",
        ),
        migrations.AddField(
            model_name="team",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ES", "España"),
                    ("MX", "México"),
                    ("PT", "Portugal"),
                    ("IT", "Italia"),
                    ("SE", "Suecia"),
                ],
                default="",
                max_length=2,
                verbose_name="País en el que juega",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino")],
                default="",
                max_length=1,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("club", "name", "gender", "country"),
                name="unique_team_per_club",
            ),
        ),
    ]
