# Generated by Django 5.1.2 on 2026-10-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_team_gender_country"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_team_per_club",
        ),
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.CharField(
                blank=True,
                choices=[
                    ("future", "Future"),
                    ("500", "500"),
                    ("1000", "1000"),
                    ("grand_slam", "Grand Slam"),
                ],
                default="",
                max_length=10,
                verbose_name="División",
            ),
        ),
    ]
