# Generated by Django 5.1.2 on 2026-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_team_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ES", "España"),
                    ("MX", "México"),
                    ("PT", "Portugal"),
                    ("IT", "Italia"),
                    ("SE", "Suecia"),
                ],
                default="",
                max_length=2,
                verbose_name="Nacionalidad del equipo",
            ),
        ),
    ]
