# Generated by Django 5.1.2 on 2026-10-03 11:44

import core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0004_team_country_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.images.team_photo_path
            ),
        ),
    ]
