# Generated by Django 5.1.2 on 2026-10-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("call", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="call.call",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
