# Generated by Django 5.1.2 on 2026-10-01 13:02

import django.db.models.deletion
import match.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("players", "0001_initial"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Victoria Local", "Victoria Local"),
                            ("Victoria Visitante", "Victoria Visitante"),
                            ("EMPATE", "Empate"),
                            ("NONE", "Ninguno"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "result_points",
                    models.CharField(blank=True, default="NONE", max_length=20),
                ),
                ("draft_mode", models.BooleanField(default=True)),
                ("season", models.CharField(blank=True, default="NONE", max_length=9)),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.club",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_matches",
                        to="team.team",
                    ),
                ),
                (
                    "visiting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visiting_matches",
                        to="team.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "n_game",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        null=True,
                    ),
                ),
                ("winner", models.CharField(max_length=10, null=True)),
                ("draft_mode", models.BooleanField(default=True)),
                (
                    "player_1_local",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_1_local",
                        to="players.player",
                    ),
                ),
                (
                    "player_1_visiting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_1_visiting",
                        to="players.player",
                    ),
                ),
                (
                    "player_2_local",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_2_local",
                        to="players.player",
                    ),
                ),
                (
                    "player_2_visiting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_2_visiting",
                        to="players.player",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="match.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("result", models.CharField(max_length=100, null=True)),
                (
                    "set1_local",
                    models.IntegerField(validators=[match.models.validate_set_value]),
                ),
                (
                    "set1_visiting",
                    models.IntegerField(validators=[match.models.validate_set_value]),
                ),
                (
                    "set2_local",
                    models.IntegerField(validators=[match.models.validate_set_value]),
                ),
                (
                    "set2_visiting",
                    models.IntegerField(validators=[match.models.validate_set_value]),
                ),
                (
                    "set3_local",
                    models.IntegerField(
                        null=True, validators=[match.models.validate_set_value]
                    ),
                ),
                (
                    "set3_visiting",
                    models.IntegerField(
                        null=True, validators=[match.models.validate_set_value]
                    ),
                ),
                ("draft_mode", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="match.game",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["club", "season", "start_date"], name="match_club_season_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("match", "n_game"), name="unique_game_number_per_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("n_game__gte", 1), ("n_game__lte", 5)),
                    ("n_game__isnull", True),
                    _connector="OR",
                ),
                name="game_number_between_1_and_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="result",
            constraint=models.UniqueConstraint(
                fields=("game",), name="unique_result_per_game"
            ),
        ),
    ]
