# Generated by Django 5.1.2 on 2026-10-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0002_match_type"),
        ("players", "0004_player_choice_none_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="removed_player_names",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_1_local",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_1_local",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_1_visiting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_1_visiting",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_2_local",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_2_local",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_2_visiting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_2_visiting",
                to="players.player",
            ),
        ),
    ]
