# Generated by Django 5.1.2 on 2026-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0003_game_keep_removed_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("enfrentamiento", "Enfrentamiento"),
                    ("reto", "Reto"),
                    ("playoff", "Play Off"),
                    ("amistoso", "Amistoso"),
                ],
                default="enfrentamiento",
                max_length=15,
                verbose_name="Tipo de partido",
            ),
        ),
    ]
