# Generated by Django 5.1.2 on 2026-10-01 13:02

import django.core.validators
import django.db.models.deletion
import players.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("team", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Derecha", "Derecha"),
                            ("Revés", "Revés"),
                            ("Mixto", " Mixto"),
                            ("NONE", "NONE"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "skillfull_hand",
                    models.CharField(
                        choices=[
                            ("Diestro", "Diestro"),
                            ("Zurdo", "Zurdo"),
                            ("NONE", "NONE"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/profile"
                    ),
                ),
                ("snp_score", models.FloatField(null=True)),
                ("in_team", models.BooleanField(default=True)),
                (
                    "joined_season",
                    models.CharField(
                        default=players.models.current_season,
                        help_text="Formato 2024-2025. Se usa para contar a cuántas convocatorias no se ha apuntado.",
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-\\d{4}$", "Usa el formato 2024-2025."
                            )
                        ],
                        verbose_name="Temporada en la que se unió",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="core.club",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="team.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SnpAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("username_encrypted", models.TextField()),
                ("password_encrypted", models.TextField()),
                (
                    "team_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Equipo en SNP"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_ok", models.BooleanField(null=True)),
                ("last_sync_message", models.TextField(blank=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snp_account",
                        to="core.club",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SnpTeamImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web del club"),
                            ("backoffice", "Back-office"),
                        ],
                        default="web",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Buscando en SNP"),
                            ("ready", "Pendiente de confirmar"),
                            ("error", "Con error"),
                            ("done", "Hecha"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("to_add", models.JSONField(blank=True, default=list)),
                ("existing", models.JSONField(blank=True, default=list)),
                ("created_players", models.JSONField(blank=True, default=list)),
                ("message", models.TextField(blank=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snp_imports",
                        to="core.club",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnpScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        default=players.models.current_season, max_length=9
                    ),
                ),
                ("date", models.DateField()),
                ("score", models.FloatField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snp_history",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "date"),
                        name="unique_snp_score_per_player_day",
                    )
                ],
            },
        ),
    ]
