# Generated by Django 5.1.2 on 2026-10-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snpaccount",
            name="last_sync_retryable",
            field=models.BooleanField(default=False),
        ),
    ]
