# Generated by Django 5.1.2 on 2026-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_snpaccount_last_sync_retryable"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino")],
                default="",
                max_length=1,
                verbose_name="Categoría",
            ),
        ),
    ]
