# Generated by Django 5.1.2 on 2026-10-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_player_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("Derecha", "Derecha"),
                    ("Revés", "Revés"),
                    ("Mixto", " Mixto"),
                    ("NONE", "—"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="skillfull_hand",
            field=models.CharField(
                choices=[("Diestro", "Diestro"), ("Zurdo", "Zurdo"), ("NONE", "—")],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
