# Generated by Django 5.1.2 on 2026-10-03 11:44

import core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_player_choice_none_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.images.player_photo_path
            ),
        ),
    ]
